// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(f
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr52EftaXl9jZsVsEiafghrseDSmHUurA',
    appId: '1:112406421214:android:85711da946d0f3eed0ac4f',
    messagingSenderId: '112406421214',
    projectId: 'assistencia-9cf8f',
    storageBucket: 'assistencia-9cf8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr52EftaXl9jZsVsEiafghrseDSmHUurA',
    appId: '1:112406421214:android:85711da946d0f3eed0ac4f',
    messagingSenderId: '112406421214',
    projectId: 'assistencia-9cf8f',
    storageBucket: 'assistencia-9cf8f.appspot.com',
    //iosClientId:
    //  '903698205588-50b57j5f6degr8b2hr78ec7n0hcmdvor.apps.googleusercontent.com',
    iosBundleId: 'com.project.asistencia',
  );
}
